### ISSUE TITLE
Heroku Logs: discord.errors.LoginFailure: Improper token has been passed.

### ISSUE THREAD

**Issue by BoQsc** [Sympthey/Disboard-Auto-Bumper#1]
## Unsuccessful trials
For this project to even succeed in building I had to remove `, bot = False` from:
<a href="https://github.com/Sympthey/Disboard-Auto-Bumper/blob/9e18a971e13c3bdf334f89bccab2f520a940c4c9/bumper.py#L27"><code> bot.run(token <del>, bot = False</del>)</code></a>
I'm not sure what's the importance of this line, but removing it the project started to build without an error.

## Everything was done in Heroku and GitHub repository.
**A Bot Token** seems to work and do get authorised. 
The known downside: bot tokens are useless as they can't bump.
`2021-05-28T11:13:41.835971+00:00 app[worker.1]: Auto Bumper Is Online!`

**A User Token** seems to not work anymore, if it ever worked.
`discord.errors.LoginFailure: Improper token has been passed.`

Conclusion: This auto bumper seems to not work for me, 
and the project is useless if the **User Token is not working**.

**Comment by Sympthey** [comment]
The line you removed tells discord.py that you are wanting to login with a user token, since you removed it you are getting the improper token passed in because you told it to expect a bot token.

What was the issue you was getting with the original code?

**Comment by BoQsc** [comment]
> The line you removed tells discord.py that you are wanting to login with a user token, since you removed it you are getting the improper token passed in because you told it to expect a bot token.
> 
> What was the issue you was getting with the original code?

```
2021-05-28T16:18:07.000000+00:00 app[api]: Build succeeded
2021-05-28T16:18:13.271458+00:00 heroku[worker.1]: Starting process with command `python bumper.py`
2021-05-28T16:18:13.946963+00:00 heroku[worker.1]: State changed from starting to up
2021-05-28T16:18:18.179718+00:00 heroku[worker.1]: Process exited with status 1
2021-05-28T16:18:18.296457+00:00 heroku[worker.1]: State changed from up to crashed
2021-05-28T16:18:18.071432+00:00 app[worker.1]: Traceback (most recent call last):
2021-05-28T16:18:18.071464+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/http.py", line 300, in static_login
2021-05-28T16:18:18.071824+00:00 app[worker.1]:     data = await self.request(Route('GET', '/users/@me'))
2021-05-28T16:18:18.071863+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/http.py", line 254, in request
2021-05-28T16:18:18.072254+00:00 app[worker.1]:     raise HTTPException(r, data)
2021-05-28T16:18:18.072538+00:00 app[worker.1]: discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
2021-05-28T16:18:18.072571+00:00 app[worker.1]: 
2021-05-28T16:18:18.083024+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2021-05-28T16:18:18.083028+00:00 app[worker.1]: 
2021-05-28T16:18:18.083038+00:00 app[worker.1]: Traceback (most recent call last):
2021-05-28T16:18:18.083038+00:00 app[worker.1]:   File "bumper.py", line 27, in <module>
2021-05-28T16:18:18.083056+00:00 app[worker.1]:     bot.run(token, bot = False)
2021-05-28T16:18:18.083057+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 723, in run
2021-05-28T16:18:18.083057+00:00 app[worker.1]:     return future.result()
2021-05-28T16:18:18.083058+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 702, in runner
2021-05-28T16:18:18.083058+00:00 app[worker.1]:     await self.start(*args, **kwargs)
2021-05-28T16:18:18.083058+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 665, in start
2021-05-28T16:18:18.083059+00:00 app[worker.1]:     await self.login(*args, bot=bot)
2021-05-28T16:18:18.083059+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 511, in login
2021-05-28T16:18:18.083418+00:00 app[worker.1]:     await self.http.static_login(token.strip(), bot=bot)
2021-05-28T16:18:18.083463+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/http.py", line 304, in static_login
2021-05-28T16:18:18.083821+00:00 app[worker.1]:     raise LoginFailure('Improper token has been passed.') from exc
2021-05-28T16:18:18.083890+00:00 app[worker.1]: discord.errors.LoginFailure: Improper token has been passed.

```

## This happens with the original code, except I uncommented `token = os.getenv`  and replaced with my user token:
<pre><code>
import discord, os, time
from discord.ext import commands


# Uncomment the line below if you are wanting to host this on heroku and are using an environment variable to store the token.
<ins><b>token = os.getenv("USER_TOKEN")</b></ins>
# If you are using this on a server or your home pc uncomment the line below and put the discord token for the account you want it to auto bump on.
#token = "TOKEN"

bot = commands.Bot(command_prefix = "--", self_bot=True)

@bot.event
async def on_ready():
    print("Auto Bumper Is Online!")




@bot.command()
async def bla(ctx):
    while True:
        await ctx.send("!d bump")
        time.sleep(8125)



bot.run(token, bot = False)
</code></pre>

**Comment by Sympthey** [comment]
> > The line you removed tells discord.py that you are wanting to login with a user token, since you removed it you are getting the improper token passed in because you told it to expect a bot token.
> > What was the issue you was getting with the original code?
> 
> ```
> 2021-05-28T16:18:07.000000+00:00 app[api]: Build succeeded
> 2021-05-28T16:18:13.271458+00:00 heroku[worker.1]: Starting process with command `python bumper.py`
> 2021-05-28T16:18:13.946963+00:00 heroku[worker.1]: State changed from starting to up
> 2021-05-28T16:18:18.179718+00:00 heroku[worker.1]: Process exited with status 1
> 2021-05-28T16:18:18.296457+00:00 heroku[worker.1]: State changed from up to crashed
> 2021-05-28T16:18:18.071432+00:00 app[worker.1]: Traceback (most recent call last):
> 2021-05-28T16:18:18.071464+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/http.py", line 300, in static_login
> 2021-05-28T16:18:18.071824+00:00 app[worker.1]:     data = await self.request(Route('GET', '/users/@me'))
> 2021-05-28T16:18:18.071863+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/http.py", line 254, in request
> 2021-05-28T16:18:18.072254+00:00 app[worker.1]:     raise HTTPException(r, data)
> 2021-05-28T16:18:18.072538+00:00 app[worker.1]: discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
> 2021-05-28T16:18:18.072571+00:00 app[worker.1]: 
> 2021-05-28T16:18:18.083024+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
> 2021-05-28T16:18:18.083028+00:00 app[worker.1]: 
> 2021-05-28T16:18:18.083038+00:00 app[worker.1]: Traceback (most recent call last):
> 2021-05-28T16:18:18.083038+00:00 app[worker.1]:   File "bumper.py", line 27, in <module>
> 2021-05-28T16:18:18.083056+00:00 app[worker.1]:     bot.run(token, bot = False)
> 2021-05-28T16:18:18.083057+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 723, in run
> 2021-05-28T16:18:18.083057+00:00 app[worker.1]:     return future.result()
> 2021-05-28T16:18:18.083058+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 702, in runner
> 2021-05-28T16:18:18.083058+00:00 app[worker.1]:     await self.start(*args, **kwargs)
> 2021-05-28T16:18:18.083058+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 665, in start
> 2021-05-28T16:18:18.083059+00:00 app[worker.1]:     await self.login(*args, bot=bot)
> 2021-05-28T16:18:18.083059+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 511, in login
> 2021-05-28T16:18:18.083418+00:00 app[worker.1]:     await self.http.static_login(token.strip(), bot=bot)
> 2021-05-28T16:18:18.083463+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/http.py", line 304, in static_login
> 2021-05-28T16:18:18.083821+00:00 app[worker.1]:     raise LoginFailure('Improper token has been passed.') from exc
> 2021-05-28T16:18:18.083890+00:00 app[worker.1]: discord.errors.LoginFailure: Improper token has been passed.
> ```
> 
> ## This happens with the original code, I only uncommented `token = os.getenv` and replaced with my user token:
> ```
> 
> import discord, os, time
> from discord.ext import commands
> 
> 
> # Uncomment the line below if you are wanting to host this on heroku and are using an environment variable to store the token.
> token = os.getenv("USER_TOKEN")
> # If you are using this on a server or your home pc uncomment the line below and put the discord token for the account you want it to auto bump on.
> #token = "TOKEN"
> 
> bot = commands.Bot(command_prefix = "--", self_bot=True)
> 
> @bot.event
> async def on_ready():
>     print("Auto Bumper Is Online!")
> 
> 
> 
> 
> @bot.command()
> async def bla(ctx):
>     while True:
>         await ctx.send("!d bump")
>         time.sleep(8125)
> 
> 
> 
> bot.run(token, bot = False)
> ```
> 
> ## The User Token is correct and should work, but it does not
> I've compared User Token to the Bot Token manually, and they are both in the same character size.
> Therefore User Token is proper and correct, and should work. But it does not.
> **I wonder if User Tokens usage may be banned. Maybe they don't work anymore, but that's just a guess.**
> ![image](https://user-images.githubusercontent.com/21064622/120016356-2b53d200-bfed-11eb-8b19-bde8e1e1b2f1.png)

I have just tested the code out myself, it is currently not working. This is no fault of the code written it is simply the discord wrapper (discord.py) needs to do some updating as discord has recently released a patch to accessing the /users/@me api. For now the code will not work but it should be working again in a couple of days!

**Comment by BoQsc** [comment]
> I have just tested the code out myself, it is currently not working. This is no fault of the code written it is simply the discord wrapper (discord.py) needs to do some updating as discord has recently released a patch to accessing the /users/@me api. For now the code will not work but it should be working again in a couple of days!

Thanks @Sympthey, you are giving me hope.

**Comment by BoQsc** [comment]
This Disboard bumper still does not work with the User Tokens.
```
2021-06-15T13:41:49.461681+00:00 heroku[worker.1]: Starting process with command `python bumper.py`
2021-06-15T13:41:50.078346+00:00 heroku[worker.1]: State changed from starting to up
2021-06-15T13:41:52.759920+00:00 heroku[worker.1]: Process exited with status 1
2021-06-15T13:41:52.839153+00:00 heroku[worker.1]: State changed from up to crashed
2021-06-15T13:41:52.685039+00:00 app[worker.1]: Traceback (most recent call last):
2021-06-15T13:41:52.685060+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/http.py", line 300, in static_login
2021-06-15T13:41:52.685366+00:00 app[worker.1]:     data = await self.request(Route('GET', '/users/@me'))
2021-06-15T13:41:52.685367+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/http.py", line 254, in request
2021-06-15T13:41:52.685445+00:00 app[worker.1]:     raise HTTPException(r, data)
2021-06-15T13:41:52.685492+00:00 app[worker.1]: discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
2021-06-15T13:41:52.685495+00:00 app[worker.1]: 
2021-06-15T13:41:52.685496+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2021-06-15T13:41:52.685496+00:00 app[worker.1]: 
2021-06-15T13:41:52.685498+00:00 app[worker.1]: Traceback (most recent call last):
2021-06-15T13:41:52.685555+00:00 app[worker.1]:   File "bumper.py", line 27, in <module>
2021-06-15T13:41:52.685687+00:00 app[worker.1]:     bot.run(token, bot = False)
2021-06-15T13:41:52.685689+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 723, in run
2021-06-15T13:41:52.685981+00:00 app[worker.1]:     return future.result()
2021-06-15T13:41:52.685986+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 702, in runner
2021-06-15T13:41:52.686363+00:00 app[worker.1]:     await self.start(*args, **kwargs)
2021-06-15T13:41:52.686367+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 665, in start
2021-06-15T13:41:52.686642+00:00 app[worker.1]:     await self.login(*args, bot=bot)
2021-06-15T13:41:52.686645+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 511, in login
2021-06-15T13:41:52.686883+00:00 app[worker.1]:     await self.http.static_login(token.strip(), bot=bot)
2021-06-15T13:41:52.686887+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/http.py", line 304, in static_login
2021-06-15T13:41:52.687142+00:00 app[worker.1]:     raise LoginFailure('Improper token has been passed.') from exc
2021-06-15T13:41:52.687200+00:00 app[worker.1]: discord.errors.LoginFailure: Improper token has been passed.
2021-06-15T13:41:52.000000+00:00 app[api]: Build succeeded

```

**Comment by BoQsc** [comment]
### Resolved: `discord.errors.LoginFailure: Improper token has been passed.`

## A new method of gaining User Token
I resoved this issue by using another method of gaining the User Token.
## Tested using: 
* Google Chrome 91.0.4472.106 
*  Windows 10 Home 

## Straight-forward tutorial
![ezgif-7-7568a8fee94c](https://user-images.githubusercontent.com/21064622/122352597-eec62700-cf57-11eb-8687-75e609070c5d.gif)

## Procedure in details
1. Create a new Discord User
2. While in the https://discord.com/channels/@me
3. Open Developer Tools (F12)
   1. Open `Application` Tab
   2. Choose `Local Storage` Tab
   3.  **Toggle `Device Tool Bar`(This is important)**
   4. Type `token` inside `Filter` input 
   5. Look for a `Key` equal to `token`
     The `Value` is the **User Token**.
4. Example of User Token:  `"ODU0OTY2MDA1MjM0NTMyMzcy.YMroGw.dqpvEMtB2V4dZRNX3WjAPjpz4PU"` 
5. Remember to remove quotes before usage: `ODU0OTY2MDA1MjM0NTMyMzcy.YMroGw.dqpvEMtB2V4dZRNX3WjAPjpz4PU`

Original Source: https://pcstrike.com/how-to-get-discord-token/

**Comment by BoQsc** [comment]
https://user-images.githubusercontent.com/21064622/122353789-1073de00-cf59-11eb-945d-31557a029423.mp4
